package:
  name: opencv3
  version: 3.1.0

source:
  fn: opencv-3.1.0.tar.gz
  url: https://github.com/Itseez/opencv/archive/3.1.0.tar.gz
  sha256: f00b3c4f42acda07d89031a2ebb5ebe390764a133502c03a511f67b78bbd4fbf
  
  patches:
    - cap_mpjpeg_decoder.patch  # [win]
    - no_rpath.patch

requirements:
  build:
   - python
   - cmake 3.6.3
   - hdf5 1.8.*      # [osx]
   - numpy >=1.10
   - eigen 3.*
   - tbb 4.3*        # [osx]
   - msinttypes r26  # [win and py<35]

  run:
   - python
   - numpy >=1.10
   - hdf5 1.8.*  # [osx]
   - tbb 4.3*    # [osx]

test:
  imports:
    - cv2
    - cv2.xfeatures2d

about:
  home: http://opencv.org/
  license: BSD
